### ISSUE TITLE
ERROR            https://localhost:3000/komikindo/komik/judulkomik

### ISSUE THREAD

**Issue by Yuri-Neko** [KatowProject/komikato_py#3]
Internal Server Error: /komikindo/komik/king-mma/
Traceback (most recent call last):
  File "/home/runner/komikatopy-5/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/runner/komikatopy-5/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/runner/komikatopy-5/routers/web/komikindo.py", line 28, in komik_detail
    komik_detail = komikindo.komik_detail(request, endpoint)
  File "/home/runner/komikatopy-5/controllers/komikindo.py", line 209, in komik_detail
    obj["alter"] = manga.find(class_="spe").find_all("span")[0].text.split(": ")[1].split(", ")
IndexError: list index out of range
[13/Mar/2023 07:48:50] "GET /komikindo/komik/king-mma/ HTTP/1.1" 500 102779
Not Found: /favicon.ico
[13/Mar/2023 07:48:51] "GET /favicon.ico HTTP/1.1" 404 3397

**Comment by KatowProject** [comment]
fixed
